name = "docle"
main = "src/index.ts"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]

# KV for run logs & index
[[kv_namespaces]]
binding = "RUNS"
id = "809528141f1a4f7b89c7d84499ee8c77"
preview_id = "d98d0473a4f34491a4c96a9f1e56afd9"

# D1 Database for SaaS (users, projects, API keys)
# Run: npx wrangler d1 create docle-db
# Then replace database_id below
[[d1_databases]]
binding = "DB"
database_name = "docle-db"
database_id = "c112bafc-9782-44be-8e29-ea4979843c14"

# Default environment (local development)
[vars]
APP_NAME = "Docle"
APP_URL = "http://localhost:3001"

# ============================================================================
# Email Configuration (Magic Links)
# ============================================================================
# For local dev: Leave these commented out and magic links will print to terminal
# For production: Set via wrangler secret or in production environment below
#
# Get your API key from: https://resend.com/api-keys
# RESEND_API_KEY = "re_..."  # Better: use `npx wrangler secret put RESEND_API_KEY --env production`
# EMAIL_FROM = "Docle <noreply@docle.co>"

# ============================================================================
# Production Environment
# ============================================================================
# Deploy to production: npx wrangler deploy --env production
# Set secrets: npx wrangler secret put RESEND_API_KEY --env production
[env.production]
[env.production.vars]
APP_URL = "https://app.docle.co"  # Update with your production frontend URL
EMAIL_FROM = "Docle <noreply@docle.co>"  # Update with your verified domain
# RESEND_API_KEY should be set via: npx wrangler secret put RESEND_API_KEY --env production

# ============================================================================
# ADVANCED: Cloudflare Sandbox with Containers (Optional - Not currently used)
# ============================================================================
# The code currently uses Cloudflare's Sandbox API directly via runInSandbox()
# which works for both local dev and production without this configuration.
# 
# Only uncomment these if you want to use the container-based approach:
# 1. Uncomment the sections below
# 2. Add to src/index.ts: export { Sandbox } from "@cloudflare/sandbox";
# 3. Deploy (containers don't work in local dev)
# ============================================================================
# [[migrations]]
# tag = "v7"
# new_sqlite_classes = ["Sandbox"]
#
# [[containers]]
# class_name = "Sandbox"
# image = "./Dockerfile"
# name = "docle-sandbox"
# max_instances = 10
#
# [[durable_objects.bindings]]
# name = "SANDBOX"
# class_name = "Sandbox"

# [observability]
# enabled = true

# Durable Object migrations
[[migrations]]
tag = "v1"
new_classes = ["CollabSession"]

# Durable Object binding for Collaborative Sessions
[[durable_objects.bindings]]
name = "COLLAB_SESSION"
class_name = "CollabSession"

