name = "docle"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# KV for run logs & index
[[kv_namespaces]]
binding = "RUNS"
id = "809528141f1a4f7b89c7d84499ee8c77"
preview_id = "d98d0473a4f34491a4c96a9f1e56afd9"

# Sandbox for secure code execution (requires Workers Paid plan)
# Note: In production, you'll need to configure this properly
# For now, we'll use the simulation fallback in local mode
# [[workflows]]
# binding = "SANDBOX"
# name = "sandbox"

[vars]
APP_NAME = "Docle"

# Durable Objects for collaborative editing
# Note: Works in production, but has issues in local dev with this Wrangler version
# Uncomment these when deploying to Cloudflare Workers
# [[durable_objects.bindings]]
# name = "COLLAB_SESSION"
# class_name = "CollabSession"

# [[migrations]]
# tag = "v1"
# new_classes = ["CollabSession"]

