name = "docle"
main = "src/index.ts"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]

# KV for run logs & index
[[kv_namespaces]]
binding = "RUNS"
id = "809528141f1a4f7b89c7d84499ee8c77"
preview_id = "d98d0473a4f34491a4c96a9f1e56afd9"

[vars]
APP_NAME = "Docle"

# NOTE: Cloudflare Sandbox with Containers requires beta access
# For now, we'll use simulation mode until containers are enabled
# [[containers]]
# class_name = "Sandbox"
# image = "./Dockerfile"
# name = "sandbox"
# max_instances = 10

# [[durable_objects.bindings]]
# name = "SANDBOX"
# class_name = "Sandbox"

# Durable Object binding for Collaborative Sessions
[[durable_objects.bindings]]
name = "COLLAB_SESSION"
class_name = "CollabSession"

